### ISSUE TITLE
CasaOS and potential walware activities

### ISSUE THREAD

**Issue by poussun-ops** [IceWhaleTech/CasaOS#106]
Hello

After a few hours of uptime, my Firewall(s) detected some strange activity coming from CasaOS on the brand new ZimaBoard

I use a very specific Firewall, named Firewalla (https://firewalla.com/). It can make deep dive analyzis of packets across the network
CasaOS has been installed for a few hours, and just connected to the network

The firewall detected connections to malware sites, in different regions, with diverse IP adresses, all in a few minutes (?)

219.155.74.133 (China)
88.95.99.218 (Norway)
189.85.35.259 (South America)
117.195.84.226 (Bangalore)
59.93.22.149 (Bangladesh)
180.188.232.98 (India)
180.188.249.132 (India)
180.176.181.15 (Taiwan)

Since, I blocked the connections and unplugged the device

Could you check what could generate these strange activities ? It might be normal, but I want to verify.

Thanks

J-F

**Comment by markstinson** [comment]
I've not check my router logs. However, one of the first things I did was delete their pre-installed, running bittorrent docker image. It could be that.

Another check to see if it's a container or not is:

ssh casaos@casaos # passwd is the account name
sudo su - 
for cid in $(docker ps | cut -d' ' -f1); do docker stop $cid; done
systemctl stop docker.service

If afterwards the traffic still exists, you'll know it's at the OS level and not buried in some container.

**Comment by JohnGuan** [comment]
Since we don't have Firewalla, there is no way to reproduce this situation with us.
Would you be able to assist in checking it out?
We currently have a few suspicions: Debian, CasaOS, Apps.

Step 1, uninstall apps
Uninstall apps one by one in the Web UI of CasaOS to see if the abnormal traffic disappears.

Step 2, uninstall CasaOS
Login to ZimaBoard via ssh
Username and password are `casaos`
Then execute `su -`
Then execute `curl -fsSL https://get.icewhale.io/casaos-uninstall.sh | bash`
Then check if the abnormal traffic disappears

If it still exists after the above actions, then we can determine what the problem is.

**Comment by JohnGuan** [comment]
The qBittorrent we pre-installed in ZimaBoard is made based on the hotio/qbittorrent image.
Is this a normal behavior of qBittorrent or a problem with the hotio/qbittorrent image? Does anyone have an idea?

**Comment by JohnGuan** [comment]
This is P2P request of hotio/qbittorrent image, just uninstall qBittorrent application.
