### ISSUE TITLE
[Feedback]homeassistant

### ISSUE THREAD

**Issue by baffee** [IceWhaleTech/CasaOS#1062]
### Description

今天我试图通过CASAOS安装Homeassistant时，系统说不兼容ARM7，可我明明之前安装过，并且成功使用过啊。这是具体是啥问题呢？谢谢

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.4.3
	 - Disk Total: 7042 
	 - Disk Used: 1951 
	 - System Info: [Armbian 22.11.0-trunk Bullseye \l Bit:32 Mem:990M Core:4 Linux onecloud 6.1.11-meson #23.02.2 SMP Fri Feb 17 22:35:23 UTC 2023 armv7l GNU/Linux]
	 - Remote Version: 0.4.3
	 - Browser: Chrome 
	 - Version: 113.0.0.0

**Comment by raller1028** [comment]
![image](https://user-images.githubusercontent.com/57336867/237019213-bba8787f-349d-4808-832f-f3e48712359a.png)
检测架构这部分出了问题,下个版本会修复,你能先使用docker-cli安装Homeassistant吗
There is a problem with the detection architecture, it will be fixed in the next release, can you install Homeassistant using docker-cli first?

**Comment by baffee** [comment]
多谢，这样我就放心了。
