### ISSUE TITLE
[Bug] arrange

### ISSUE THREAD

**Issue by Avey777** [IceWhaleTech/CasaOS#1066]
_____                 ____   _____ 
  / ____|               / __ \ / ____|
 | |     __ _ ___  __ _| |  | | (___  
 | |    / _` / __|/ _` | |  | |\___ \ 
 | |___| (_| \__ \ (_| | |__| |____) |
  \_____\__,_|___/\__,_|\____/|_____/ 
                                      
   --- Made by IceWhale with YOU ---

[  OK  ] Your hardware architecture is : x86_64
[  OK  ] Your System is : Linux
[  OK  ] Your Linux Distribution is : debian 
[  OK  ] Memory capacity check passed.
[  OK  ] Disk capacity check passed.
Get:1 https://download.docker.com/linux/debian buster InRelease [54.0 kB]
Get:2 https://download.docker.com/linux/debian buster/stable amd64 Packages [37.8 kB]
Hit:3 http://mirrors.ucloud.cn/debian buster InRelease
Get:4 http://mirrors.ucloud.cn/debian-security buster/updates InRelease [34.8 kB]
Hit:5 http://download.zerotier.com/debian/buster buster InRelease                    
Get:6 http://mirrors.ucloud.cn/debian buster-updates InRelease [56.6 kB]
Get:7 https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease [7,505 B]
Err:7 https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ABA1F9B8875A6661
Get:8 http://mirrors.ucloud.cn/debian-security buster/updates/main Sources [330 kB]
Get:9 http://mirrors.ucloud.cn/debian-security buster/updates/main amd64 Packages [486 kB]
Get:10 http://mirrors.ucloud.cn/debian-security buster/updates/main Translation-en [265 kB]
Reading package lists... Done            
W: GPG error: https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY ABA1F9B8875A6661
E: The repository 'https://dl.cloudsmith.io/public/caddy/stable/deb/debian any-version InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by raller1028** [comment]
You need to check your network first (need scientific internet access), then apt-get update

**Comment by raller1028** [comment]
If still have problems please reopen

**Comment by molsattva861** [comment]
--- Made by IceWhale with YOU ---            
[  OK  ] Your hardware architecture is : aarch64
[  OK  ] Your System is : Linux                 [  OK  ] Your Linux Distribution is : debian
[  OK  ] Memory capacity check passed.
[  OK  ] Disk capacity check passed.
Hit:1 http://mirrors.163.com/debian buster InRelease
Hit:2 http://mirrors.163.com/debian buster-updates InRelease
Get:3 http://mirrors.163.com/debian buster-backports InRelease [51.4 kB]
Err:3 http://mirrors.163.com/debian buster-backports InRelease                                    The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
Hit:4 http://mirrors.163.com/debian-security buster/updates InRelease
Reading package lists... Done
W: GPG error: http://mirrors.163.com/debian buster-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0E98404D386FA1D9 NO_PUBKEY 6ED0E7B82643E131
E: The repository 'http://mirrors.163.com/debian buster-backports InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
