### ISSUE TITLE
[Bug] Homeassistant installation on raspberry pi fails

### ISSUE THREAD

**Issue by dante-haversham** [IceWhaleTech/CasaOS#1068]
Hello everybody!

**Describe the bug**
HomeAssistant cannot be installed on raspberry pi 64Bit.

**To Reproduce**
1. Go to App store an click on install HomeAssistant on Raspbi 64 bit.
2. Installation remains at 0%

**Expected behavior**
HomeAssistant should be installable as all the the other containers do. Other containers installed flawlessly. At least it should not get stuck and some information should be delivered about the unsuccessful installation.

**Screenshots**

![image](https://github.com/IceWhaleTech/CasaOS/assets/29981719/f382c270-a03d-4ddc-a0a8-2b01017dd7ff)
![image](https://github.com/IceWhaleTech/CasaOS/assets/29981719/7cc79b3c-b79b-4570-afe4-b5c28946cf0e)
![image](https://github.com/IceWhaleTech/CasaOS/assets/29981719/e9b8730d-a848-4902-a171-1583f412535f)

**Desktop (please complete the following information):**
 - OS: Linux rpi1 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
 - Browser Chrome Version 112.0.5615.139 (Offizieller Build) (64-Bit)
 - Version CasaOS 0.4.3

**Logs**

run following command to collect corresponding logs:
See attachments, since the logdump ist huge.

**Additional context**
This system is 64 bit:
```
root@rpi1:~# uname -a
Linux rpi1 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
```
When pulling the HomeAssistant image manually, it cannot be found:
```
root@rpi1:~# docker pull linuxserver/homeassistant:latest
latest: Pulling from linuxserver/homeassistant
no matching manifest for linux/arm/v8 in the manifest list entries
```

Maybe it is the architecture string (v8 vs arm64v8 on docker hub) that's hindering docker to download the image?

Regards,
Dante.
[casaos-logs.txt](https://github.com/IceWhaleTech/CasaOS/files/11435409/casaos-logs.txt)

**Comment by raller1028** [comment]
There is a problem with the detection architecture, it will be fixed in the next release, can you install Homeassistant using docker-cli first?

**Comment by henrikhjelmjobb** [comment]
is there a setting in store app, 
so the store app knows what platform it is on. 
i belive that can be away to fix problem like this. 

normal install use -> linuxserver/homeassistant:latest
raspberry pi use -> homeassistant/raspberrypi4-homeassistant

**Comment by dante-haversham** [comment]
> is there a setting in store app, so the store app knows what platform it is on. i belive that can be away to fix problem like this.
> 
> normal install use -> linuxserver/homeassistant:latest raspberry pi use -> homeassistant/raspberrypi4-homeassistant
I'm not sure the question is for me ;-) but at least I'm not aware of a configuration option in the UI.

**Comment by stef609** [comment]
Hello, I have exactly the same issue.  Also running in raspberry4.  Same error when trying a docker pull of the image.

**Comment by raller1028** [comment]
@stef609 Is the linux architecture on your rpi4 armv7 or arm64?
You can try to upgrade to 0.4.4-alpha and try to install homeassistant again, or you can choose not to upgrade and install it manually on v0.4.3 using the command line.

**Comment by stef609** [comment]
I have this:
uname -a
Linux moebius 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux.
I’ll try with a manual installation.  Thanks!

**Comment by raller1028** [comment]
The version of linuxserver/homeassistant selected by the new version of the App Store is a newer version, but it does not include the armv7 architecture, so if you want to install homeassistant on armv7 device, we recommend that you go to hub.docker.com to find out the version of the corresponding architecture that is supported by the application that you need. 

To install armv7 homeassistant, you need to find /var/lib/casaos/appstore/*/*/_appstore-main/Apps/HomeAssistant/docker-compose.yml and put `image. linuxserver/homeassistant:2023.6.3` to `image: linuxserver/homeassistant:2023.4.6` (because this version supports armv7 architecture).
![image](https://github.com/IceWhaleTech/CasaOS/assets/57336867/f0a06894-daf3-4611-9546-8833519852d8)
![image](https://github.com/IceWhaleTech/CasaOS/assets/57336867/d3309de2-2a93-4d0a-941f-b5f6a1961705)


After modifying the file, copy the contents of this file, use the install a customized app, paste the contents and install it.
![image](https://github.com/IceWhaleTech/CasaOS/assets/57336867/5f861181-142c-4f9a-a8ae-d6b5760acbd5)

**Comment by raller1028** [comment]
If still have problems, please reopen
