### ISSUE TITLE
Hdd always in use (noise)

### ISSUE THREAD

**Issue by williams407** [IceWhaleTech/CasaOS#1102]
Hi,
I installed Casaos on my zimaboard 832 , i plug an seagate 12tb through the sata port , is correctly detected and formated but i ear always a noise like the disk is in use but it stop , and it start again , and it stop , and always and always, i am afraid about the longevity of my drive , can someone help me ?

Ty

**Comment by raller1028** [comment]
What version of CasaOS are you using? In the past, there was an older version that would continuously wake up the HDD due to health checks. Therefore, we recommend upgrading to our latest version.

How are you stopping your hard drive? I tried using the hdparm command, and it does have some effect by putting my hard drive into sleep mode. However, whenever I read or write to the hard drive, it wakes up. For completely stopping the hard disk drive, unmounting (umount) is the most reliable and safe strategy. By unmounting the file system, you can ensure that all access to the hard disk drive is terminated.

**Comment by raller1028** [comment]
If still have problems, please reopen

**Comment by sethml** [comment]
So, I just ran into something that seems like this problem, and I eventually tracked down what was going on. Long story short: after formatting with ext4, the `ext4lazyinit` kernel process slowly zeros out the inode tables, as [explained here](https://www.linuxquestions.org/questions/linux-general-1/someone-please-explain-ext4lazyinit-to-me-4175658874/). This process can take a very long time, and involves about a disk access per second. On my 18TB mechanical hard drive, this resulted in fairly loud periodic clicking after formatting the drive. Presumably it would complete in a few days. Any large IO operations, such as copying large files to the drive, would be significantly slowed during that time. Not ideal for a NAS.

I was curious whether it'd be reasonable to pass the appropriate flags to mkfs to zero the inode table at filesystem creation time. The answer is - sort of. For my 18TB drive, filesystem creation took 52 seconds with lazy initialization and 12 minutes 18 seconds without. It turns out this was slower than necessary due to a misaligned partition (see #1933). With a properly aligned partition, it took 27 seconds with lazy initialization and it took 7 minutes 20 seconds without.

Maybe it would be reasonable to give an option in the Storage Manager to format without lazy initialization, and warn that with lazy initialization the drive will have constant access and be slow for a while after filesystem creation?

<details>
<summary>With lazy initialization and misaligned partition:</summary>

```
casaos@casaos:~$ time sudo mkfs.ext4 -F /dev/sda1
mke2fs 1.46.2 (28-Feb-2021)
/dev/sda1 contains a ext4 file system
	last mounted on /mnt/a16tb on Wed Jul 31 20:41:20 2024
/dev/sda1 alignment is offset by 3072 bytes.
This may result in very poor performance, (re)-partitioning suggested.
Creating filesystem with 4394582007 4k blocks and 274661376 inodes
Filesystem UUID: c67551e2-82ef-490c-ae43-82a888bc9886
Superblock backups stored on blocks:
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208,
	4096000, 7962624, 11239424, 20480000, 23887872, 71663616, 78675968,
	102400000, 214990848, 512000000, 550731776, 644972544, 1934917632,
	2560000000, 3855122432

Allocating group tables: done
Writing inode tables: done
Creating journal (262144 blocks): done
Writing superblocks and filesystem accounting information: done


real	0m51.685s
user	0m0.387s
sys	0m1.799s
```
</details>

<details>
<summary>Without lazy initialization, with misaligned partition:</summary>

```
casaos@casaos:~$ time sudo mkfs.ext4 -F -E lazy_itable_init=0 /dev/sda1
mke2fs 1.46.2 (28-Feb-2021)
/dev/sda1 alignment is offset by 3072 bytes.
This may result in very poor performance, (re)-partitioning suggested.
Creating filesystem with 4394582007 4k blocks and 274661376 inodes
Filesystem UUID: a8b1c3cd-0797-40a3-9971-d7c9ee40efaf
Superblock backups stored on blocks:
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208,
	4096000, 7962624, 11239424, 20480000, 23887872, 71663616, 78675968,
	102400000, 214990848, 512000000, 550731776, 644972544, 1934917632,
	2560000000, 3855122432

Allocating group tables: done
Writing inode tables: done
Creating journal (262144 blocks): done
Writing superblocks and filesystem accounting information: done


real	12m18.271s
user	0m4.389s
sys	0m19.118s
```
</details>

<details>
<summary>With lazy initialization and aligned partition:</summary>

```
casaos@casaos:~$ time sudo mkfs.ext4 -F /dev/sda1
mke2fs 1.46.2 (28-Feb-2021)
/dev/sda1 contains a ext4 file system
	created on Wed Jul 31 23:42:10 2024
Creating filesystem with 4394581755 4k blocks and 274661376 inodes
Filesystem UUID: d7f7c186-3085-4262-a910-d847489fc063
Superblock backups stored on blocks:
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208,
	4096000, 7962624, 11239424, 20480000, 23887872, 71663616, 78675968,
	102400000, 214990848, 512000000, 550731776, 644972544, 1934917632,
	2560000000, 3855122432

Allocating group tables: done
Writing inode tables: done
Creating journal (262144 blocks): done
Writing superblocks and filesystem accounting information: done


real	0m27.059s
user	0m0.390s
sys	0m1.465s
```
</details>

<details>
<summary>Without lazy initialization, with aligned partition:</summary>

```
casaos@casaos:~$ time sudo mkfs.ext4 -F -E lazy_itable_init=0 /dev/sda1
mke2fs 1.46.2 (28-Feb-2021)
Creating filesystem with 4394581755 4k blocks and 274661376 inodes
Filesystem UUID: 5145e8e0-10c5-4feb-8a82-047df811ad36
Superblock backups stored on blocks:
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208,
	4096000, 7962624, 11239424, 20480000, 23887872, 71663616, 78675968,
	102400000, 214990848, 512000000, 550731776, 644972544, 1934917632,
	2560000000, 3855122432

Allocating group tables: done
Writing inode tables: done
Creating journal (262144 blocks): done
Writing superblocks and filesystem accounting information: done


real	7m20.526s
user	0m4.238s
sys	0m17.983s
```
</details>

**Comment by sethml** [comment]
It doesn't look like I can reopen this issue. If you think this is worth addressing, please reopen, or suggest that I create a new feature request.

**Comment by quackextractor** [comment]
Thanks @sethml, this worked for me.
