### ISSUE TITLE
[Feedback] Auto-assign random available port for WebUI if the app's default WebUI port is already in use

### ISSUE THREAD

**Issue by WisdomSky** [IceWhaleTech/CasaOS#1140]
### Description

There are some apps whose default port is set to either 80 or 8080 since this is a common practice to use these ports for dashboards or WebUIs.  

Would be awesome if CasaOS can fallback to a random available (not in use) port if ever the installation detected that the default port set in the app is already in use by an another (docker) app (or any service in the host).

### Additional Information

For example, I attempted to install PHPMyAdmin, whose default port is 80 but the installation stopped since the port is already in use and then opened the settings to make changes so that the installation can proceed:

![image](https://github.com/IceWhaleTech/CasaOS/assets/6792172/bdcdc6c9-11fa-497d-958d-6a95f7624e12)

It would be awesome and will create a better user experience if CasaOS can seamlessly handle this situation by auto-assigning it to an another port instead like:

![image](https://github.com/IceWhaleTech/CasaOS/assets/6792172/57f0073c-95b5-4fc2-b82a-103952ae6ad0)

To avoid surprises, the user can also be prompted with a dialog:

![image](https://github.com/IceWhaleTech/CasaOS/assets/6792172/70a9695b-59e0-418a-92ea-2ee262a005ec)

**Comment by tigerinus** [comment]
Voice heard.

We had this function, which updates any port that runs into conflict, in the past.

We removed it because we think CasaOS should not make decision on behalf of users.

For example in some cases user expect the port to be fixed, e.g. port 53 for Pi-hole - port 53 is a designated port for DNS that cannot be set to a different port in the system. When CasaOS randomly assign a new port instead of port 53 (it almost always happens on Ubuntu because of `resolved` daemon always occupies port 53), and the entire network relying on pi-hole stops working.

That said, I think maybe it's not that bad if we only pick random port for WebUI. The only caveat is when user have a bookmark pointing to the old port, then that bookmark no longer works when CasaOS decides to give a new port number.

**Comment by WisdomSky** [comment]
Yes, what I mean is really only about the WebUI. 

I understand the case about the other ports like when attempting to install Pi Hole but you have Adguard Home installed, these will definitely cause a conflict.  So the user should resolve it by himself. He can either uninstall Adguard first before installing PiHole. Port 53 is a standard port for DNS Servers, it makes sense to not meddle with it.

But for WebUI where it's inevitable to have multiple apps using the very same port (:80) for their web servers, and CasaOS have a convenient WebUI Port field to tell CasaOS the port where the web UI is running. 

As for the case regarding the bookmark, it wouldn't hurt for the user if he verifies the webui port from CasaOS and update the bookmark accordingly.  Also in most cases, if we create a bookmark, we only do it after the app was installed and running. Unless he removed a container and installed a new one, but that said, it should give him the idea that the port has been changed so first thing he'll check is to verify the port where it is now running.

**Comment by tigerinus** [comment]
This should be covered by

https://github.com/IceWhaleTech/CasaOS/issues/1178#issuecomment-1588496181
