### ISSUE TITLE
[Alpha][Bug] Lost the hability to edit existing containers after updating CasaOS from 0.4.3 to 0.4.4 Alpha

### ISSUE THREAD

**Issue by IaonnisPrysma** [IceWhaleTech/CasaOS#1145]
### What happened?

Every single of my old containers lost the hability to edit them, and since the feature of importing a file still doesn't exist reimporting them and configuring all of them again would be tedious, is there a way to fix these old containers?

### Screenshots

![image](https://github.com/IceWhaleTech/CasaOS/assets/134575902/1d976e90-3d8a-460a-b2fd-b7b2f05f60a2)

**Comment by ChristopherHaws** [comment]
I have this same issue. I thought that it was because of adding a 2nd app store, but even custom containers which I added in v0.4.3 are not editable after updating.

In the meantime while this issue is being fixed, is there a way to modify these apps manually using terminal or the files app?

Thanks!

**Comment by IaonnisPrysma** [comment]
I didn't even added the 2nd App Store so... Not the issue origin. I went the "easy route" by backing up the data from the containers, uninstalling them, then installing them again, but this is kinda easy as I already had the .json for the containers backed up. If you don't have those it would be harder, and may depend on your container if there are setting files on them.

But, surprisingly, docker doesn't allow to modify existing containers enviroment variables after creation, so you will need to wait until this is fixed, or just delete your old containers and start them again...

**Comment by tigerinus** [comment]
> I have this same issue. I thought that it was because of adding a 2nd app store, but even custom containers which I added in v0.4.3 are not editable after updating.
> 
> In the meantime while this issue is being fixed, is there a way to modify these apps manually using terminal or the files app?
> 
> Thanks!

You can try to revert back to 0.4.3 by running

```shell
curl -fsSL get.casaos.io | sudo bash
```

**Comment by IaonnisPrysma** [comment]
Yep, I tried and the apps that were missing the "Settings" button are now back having it and all the container info is right, no corruption or issues in between

For anyone that needs this; if you're using a custom port for CasaOS WebUI, use:

`curl -fsSL get.casaos.io -u "localhost:PORT" | sudo bash`

PORT is of course, your port

**Comment by ETWang1991** [comment]
Due to some technical solution adjustments, in v0.4.4 we have adjusted the installation method of Docker, thus the new version is disconnected from the old one. Hopefully you noticed that this issue was publicized in 0.4.4 Alpha, which is still in an experimental phase and is not something that happens with every upgrade.
