### ISSUE TITLE
[Bug] Cannot connect to the Docker daemon

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#1299]
Hello
After running the command `wget -qO- https://get.casaos.io | bash` and try to install CasaOS on a Debian 12 VPS I got the following error I tried different method of reinstalling docker and such but each time time stuck in here.

```Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?```

**Comment by raller1028** [comment]
We have recently tried to run debian 12 on arm64 and install casaos-v0.4.4 it works fine !
Can I assume that this issue is a problem with the debian 12 docker daemon on amd64? I'll try running docker on debian 12 and see if I can find a solution for the docker daemon. Or do you have any suggestions specific to solving the docker daemon

**Comment by AuthorShin** [comment]
@raller1028 I have Debian 12 and CasaOS installed together on like 3 of my machines and they are working fine (same thing happened on another one first but after uninstalling docker and running the CasaOS installation script it worked fine but on this particular it didn't work even I tried to install docker manually which didn't solve the problem) also I looked up for solutions which none worked for my case on this machine.

**Comment by LinkLeong** [comment]
Is your docker running properly?

**Comment by AuthorShin** [comment]
@LinkLeong 

I get the following after running `docker version`
```
Client: Docker Engine - Community
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:35:35 2023
 OS/Arch:           linux/amd64
 Context:           default
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by tigerinus** [comment]
@AuthorShin - I logged into the environment via SSH.

It looks like Docker daemon could not get started due to 

```
failed to start daemon: Error initializing network controller: error creating default "bridge" network: Failed to Setup IP tables: Unable to enable NAT rule:  (iptables failed: iptables --wait -t nat -I POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE: Warning: Extension MASQUERADE revision 0 not supported, missing kernel module?
```

I tried to load the `nf_nat` module but no luck:

```shell
# modprobe nf_nat
modprobe: ERROR: could not insert 'nf_nat': Unknown symbol in module, or unknown parameter (see dmesg)
```

Looking into `dmesg` I see a whole bunch of errors like

```
[967655.709153] BPF: [99718] ENUM T_ASSURED
[967655.711238] BPF: size=4 vlen=14
[967655.712312] BPF:
[967655.713122] BPF: Invalid name
[967655.714031] BPF:
[967655.714732] failed to validate module [nf_conntrack] BTF: -22
[967655.722623] missing module BTF, cannot register kfuncs
```

I cannot investigate further as this is beyond the scope of CasaOS, but more of a kernel issue of your Linux environment.

Note that Debian 12 aka `bookworm` is still in test phase, so issue like this might be expected. I suggest you reach out to Debian developer community and report this issue for help.

**Comment by AuthorShin** [comment]
@tigerinus Thanks a lot Tiger
Yeah I realized that When using cloud based VPS from providers which they have they own pre-config script etc modifying it these kind of networking problem might happens whereas if I install the Debian 12 from ISO there won't be a problem like this.
Again thanks a lot for all the time and effort you guys put in this @tigerinus @LinkLeong
