### ISSUE TITLE
Jellyfin Rassberry Pi Error [Bug] 

### ISSUE THREAD

**Issue by underling3311** [IceWhaleTech/CasaOS#1319]
**Describe the bug**

Jellyfin Rassberry Pi install Error. Not installing arm version of jellyfin. I upgraded my other jellyfin server on a rassberry pi same thing. 

**To Reproduce**

1. Go to jellyfin in app store
2. Install
3. Shows Error

**Screenshots**

> If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

```
 - OS: [e.g. iOS]
 - Browser [e.g. librewolf]
```
![casaos](https://github.com/IceWhaleTech/CasaOS/assets/49108816/42ad8d0c-3af3-4711-94d0-4e7a30fda351)

**Comment by raller1028** [comment]
Because the current version of the app store part of the application is the latest version, but this latest version does not contain armv7 architecture
This is the default version installed in the app store.
![image](https://github.com/IceWhaleTech/CasaOS/assets/57336867/05dbb70e-f59b-457b-8764-9a84ed7161b6)
You can see at hub.docker.com that this version only supports amd64 and arm64.
So if you want to download the armv7 version, you need to replace the version number I mentioned above.
replace image: linuxserver/jellyfin:10.8.10 with image: linuxserver/jellyfin:arm32v7-10.8.10
Save it and copy the whole thing, then install the armv7 version of the application by customizing the install-import.
![image](https://github.com/IceWhaleTech/CasaOS/assets/57336867/a363c79d-7b7a-49d9-ae81-80196f93fc0d)

**Comment by Quato38** [comment]
i have the same problem

**Comment by bright002** [comment]
i have the same problem

**Comment by jerrykuku** [comment]
As [raller1028](https://github.com/raller1028) said. The current version of Jellyfin in our store does not support armv7.
Maybe you need to manually install a version that supports armv7. Or install the RpiOS 64bit.

**Comment by jerrykuku** [comment]
This Issue hasn't been updated for over 14 days, I will close it. if you still have problems you can reopen it or create a new Issue.
