### ISSUE TITLE
[Bug] 在files中上传错误

### ISSUE THREAD

**Issue by KENKshachu0** [IceWhaleTech/CasaOS#1436]
上传视频文件时（任何拓展名）会出现上传错误：如上传1gb的文件：则会上传1.2gb后卡住（显示为1.2gb/1gb），之后显示出现错误，但已成功上传

	+-+OS%3A+linux
	+-+CasaOS+Version%3A+0.4.4.2
	+-+Disk+Total%3A+56927+
	+-+Disk+Used%3A+17678+
	+-+System+Info%3A+[Debian+GNU%2FLinux+12+++\l+Bit%3A64+Mem%3AM+Core%3A4+Linux+KENK+6.1.0-12-amd64+%231+SMP+PREEMPT_DYNAMIC+Debian+6.1.52-1+(2023-09-07)+x86_64+GNU%2FLinux]
	+-+Remote+Version%3A+
	+-+Browser%3A+Edge+
	+-+Version%3A+117.0.2045.47

**Comment by LinkLeong** [comment]
大小的问题，是换算单位的问题导致的。上传实际成功，但却显示失败这个问题我们发现了，最近的处理是把错误放出来，给用户明确错误信息。你说的两个问题我们会在进行跟踪，感谢你的反馈。
The problem with the size is caused by a problem with converting units. The issue of uploading actually succeeding but showing failure is one we've found, and have recently dealt with by putting up the error and giving the user a clear error message. We'll be following up on the two issues you mentioned, thanks for the feedback.
