### ISSUE TITLE
[Bug] CasaOS does n  ot finish install on Debian or ubuntu

### ISSUE THREAD

**Issue by fethomm** [IceWhaleTech/CasaOS#1553]
**Describe the bug**

After downloading some dependencies, install stops: 
main line 567: pushd: /tmp/casaos-installer/tmp.tSo3NctxXb: permission denied

**To Reproduce**
run the script
> Steps to reproduce the behavior:

**Expected behavior**

Install should finish

**Screenshots**

> If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

```
 - OS: [e.g. iOS] Debian 12, TuxedoOS 2, Ubuntu 23.10
 - Browser [e.g. chrome, safari] Firefox 119
 - Version [e.g. 22]
```

**System Time**

> Run `timedatectl` and share the output

```
(timedatectl output here)
```

**Logs**

> Run following command to collect corresponding logs:

```bash
sudo journalctl -xef -u casaos-gateway
sudo journalctl -xef -u casaos-user-service
sudo journalctl -xef -u casaos-local-storage
sudo journalctl -xef -u casaos-app-management
sudo journalctl -xef -u casaos.service
```

**Additional context**

> Add any other context about the problem here.
> 
> If you are a Zimaboard user, make it explicit with when you got your Zimaboard.

**Comment by SchBenedikt** [comment]
Hello @fethomm,
In any case, you can try running the code with “sudo”, or simply delete the temporary directory and then restart the computer again (to update the rights). But it seems that it is because of line 567, which says the following:
Show 2 "Downloading ${PACKAGE}...". So it's an error because you don't have permission to install?
Alternatively, you can try running “sudo apt-get update && sudo apt-get upgrade” first, or use another code (i.e. with wget (wget -qO- https://get.casaos.io | sudo bash)). .
It's best to try again after a restart, maybe it will work then.
Best regards,
schBenedikt
Original comment:
[Casaos installieren](https://technik.xn--schchner-2za.de/blog/2022/08/31/casaos-installieren/)

**Comment by fethomm** [comment]
What worked in the end was `curl -fsSL https://get.casaos.io | sudo bash`.

**Comment by udance4ever** [comment]
@fethomm glad you got it to work!   nudge to close this issue as completed :)

**Comment by charlye30** [comment]
thank u worked "curl -fsSL https://get.casaos.io | sudo bash" after a lot of attempts on windows 11 wsl2
