### ISSUE TITLE
[Alpha][Bug]  App Store Problem

### ISSUE THREAD

**Issue by djreiner** [IceWhaleTech/CasaOS#1661]
### What happened?

App Store will NOT load.  "Spins" and will not allow exit.  Must reload the web UI to get access to CasaOS.

**Comment by dragonfire1119** [comment]
I made a script to fix this: https://community.bigbeartechworld.com/t/fix-the-casaos-app-store-not-loading/593?u=dragonfire1119

**Comment by CharlesCanlom** [comment]
> I made a script to fix this: https://community.bigbeartechworld.com/t/fix-the-casaos-app-store-not-loading/593?u=dragonfire1119

Give out this 'App store with the specified URL not found.' message.

**Comment by djreiner** [comment]
Fantastic!!! Fixed because of YOU!!!! Thank you.

**Comment by CorrectRoadH** [comment]
dup of #1659

Thank your for your feedback🙏. The issue have fixed. the Bug is caused by the robustness of CasaOS not strong.🥲We already have a lot of moves to improve the robustness now.🥺

https://github.com/IceWhaleTech/CasaOS-AppStore/pull/414
https://github.com/IceWhaleTech/CasaOS-AppManagement/pull/154
https://github.com/IceWhaleTech/CasaOS-UI/commit/7d257eabe5bf8f4011b436761a376458c0a50f3e
