### ISSUE TITLE
[Bug]  appstore

### ISSUE THREAD

**Issue by uconsaa** [IceWhaleTech/CasaOS#1662]
appstore does not load even after a restart rendering it pretty much useless
![CasaOS – Mozilla Firefox 27_01_2024 01_21_36](https://github.com/IceWhaleTech/CasaOS/assets/112803172/0ed0ba1a-5fcf-459b-97bf-539a2305e38d)

**Comment by dilun0851** [comment]
How do you solve problems with the Casa OS app store?

**Comment by dilun0851** [comment]
How do you solve problems with the Casa OS app store?

**Comment by DNASystem** [comment]
idem stesso problema aggiornato alla v0.4.6 appstore inutilizzabile

**Comment by dragonfire1119** [comment]
I made a script to fix this: https://community.bigbeartechworld.com/t/fix-the-casaos-app-store-not-loading/593?u=dragonfire1119

**Comment by CorrectRoadH** [comment]
Thank your for your feedback. The issue have fixed. the Bug is caused by the robustness of CasaOS not strong.🥲We already have a lot of moves to improve the robustness now.
- https://github.com/IceWhaleTech/CasaOS-AppStore/pull/414
- https://github.com/IceWhaleTech/CasaOS-UI/commit/7d257eabe5bf8f4011b436761a376458c0a50f3e
