### ISSUE TITLE
BUG: Web SSH client doesn't allow login

### ISSUE THREAD

**Issue by Protektor-Desura** [IceWhaleTech/CasaOS#221]
I am not able to ssh in and login to the server using the web interface. I get the following error after my login and password.

ssh: handshake failed: read tcp 127.0.0.1:26790->127.0.0.1:22: read: connection reset by peer

The server host OS is Ubuntu 20.04.4 LTS and all the updates have been applied.

**Comment by tigerinus** [comment]
Hello

Can you do `ssh -v` and paste the verbose information here?

Appreciated!

**Comment by tigerinus** [comment]
@Protektor-Desura I'm gonna close this issue for now. However if you see this problem happening again, please open a new issue and let the team know. Thanks!

**Comment by Protektor-Desura** [comment]
Still getting the same error on v0.3.1.1 when I try and SSH in the server from the web interface.

login:protektor
password:
ssh: handshake failed: read tcp 127.0.0.1:35742->127.0.0.1:22: read: connection reset by peer
login:

Can you do ssh -v and paste the verbose information here?
No because it isn't a problem with the server or SSH daemon. 

I can use Putty from the same machine as running the web client and it works no problem. I am using Chrome Version 101.0.4951.67 (Official Build) (64-bit) on Windows. Firefox 100.0.2 (64-bit) is doing the same exact thing. 

The problem is not the SSH daemon, but the what ever the client is in the web interface. As I have said I have no problem getting to the server with other SSH clients, just not the web interface.

**Comment by tigerinus** [comment]
@Protektor-Desura - The team is working on allowing extra SSH arguments when initiating SSH session from the web UI - by then we should be able to investigate issues like this by adding `-v`.

That said, the error `connection reset by peer` indicates that server side is reached but somehow server rejected the handshake (Otherwise it would be `Connection refused`). Thus there might be something in the SSHD log.

Can you do following commands after reproing the issue and see anything interesting there?

```bash
journalctl _COMM=sshd
journalctl -t sshd -e
```
