### ISSUE TITLE
RPI OS fails to boot

### ISSUE THREAD

**Issue by tanmay-pathak** [IceWhaleTech/CasaOS#59]
**Bug**
OS fails to boot because of a failed start job trying to mount the SSD where CasaOS is installed. 

**Steps to reproduce the behaviour**:
1. Install CasaOS on a newly flashed Raspberry Pi OS Lite or Desktop on an external HDD/SSD.
2. Do the basic setup of setting up a user. 
3. Do a reboot.
4. See error `"Timed out waiting for device /dev/disk/by-partuuid/<uuid_of_SSD/HDD>"`.

**Expected behavior**
A fresh OS image with just CasaOS should reboot just fine. I faced this issue with both Raspberry Pi OS Lite and Desktop. Also I tried flashing the OS on an SD card then installing CasaOS. But, as soon as you attach an external drive and reboot, it fails. 

**Addtional ERROR Messages:**
```
[TIME] Timed out waiting for device /dev/disk/by-partuuid/<uuid_of_SSD/HDD>
[DEPEND] Dependency failed for /boot.
[DEPEND] Dependency failed for Local File Systems.
[DEPEND] Dependency failed for File System Check on /dev/disk/by-partuuid/<uuid_of_SSD/HDD>
```

**System Information:**
 - OS: Raspberry Pi OS Lite (32-bit)
 - Hardware: Raspberry Pi-4 4GB RAM
 - CasaOS Version: v0.2.3

**Comment by tigerinus** [comment]
@tanmay-pathak which `systemd` service gives that `Timed out waiting for device`?

**Comment by tanmay-pathak** [comment]
> @tanmay-pathak which `systemd` service gives that `Timed out waiting for device`?

I uninstalled CasaOS but I can do a fresh install again to find that info for you. How would I check that?

**Comment by LinkLeong** [comment]
I am trying to solve this problem, but I need more information.
1. Are you booting the hard drive or the T-F card?
2. is the casaos installation installed on the boot system?
@tanmay-pathak

**Comment by tanmay-pathak** [comment]
@LinkLeong 
1) When I opened this issue I had tried installing RPi OS once on the Micro SD card and once on my SSD. With both approach I faced the same issue. Both times, I made sure to change the boot priority respectively. 
2) No, my boot system was just 256MB and I am pretty sure CasaOS did the default installation on my other partition. Two folders that I saw newly created were `/casaOS` and `/DATA` where `/` was my other partition. 

If you would like me to install it a specific way let me know I will do it on my spare Pi.

**Comment by originalgoon** [comment]
I experienced this same issue every time I installed casaOS on a rasp 4 4gb bullseye w/ssd boot.
I got around it by booting to an SD and repairing the bootloader, switched the config back to boot from USB first.
Weird thing is I had to keep the sd installed for it to boot correctly.
As soon as I take it out, it does the same this all over again.

**Comment by originalgoon** [comment]
I'm by no means a code writer, but it seems its got something to do with how casaOS is setting up its volumes/binding i fiddled with it last night and installed docker manually first, then installed casaOS with different bindings and didn't experience these issues.
i can confirm this this is not an issue on Ubuntu server 20.04 & 21.10 while on a raspberry pi

**Comment by musklor** [comment]
I tried 32bits and 64bits RPI Os, same issue.

**Comment by Orohym** [comment]
Hello, I experienced the same problem as you. I did some research and it seams that the problem comes from the auto-usbmount feature of casaOS. 
Since we are using a SSD for the raspberry pi OS, casaOS doesn't know that and try to mount the "OS SSD" as a "normal" usb storage device.  

So, i found a "brut-force" solution.
First, use `blkid` command. You should have a list that looks like (if you have 1 SSD and another USB storage device):

- `/dev/sda1`
- `/dev/sda2`
- `/dev/sdb1`
- `/dev/sdb2`

Then, identify your boot disk (should be a boot written somewhere).
For me it was `/dev/sda1` and `/dev/sda2`. Keep this in mind.

Now, you have to edit the file `/casaOS/server/shell/11-usb-mount.rules`.
Use the command`sudo nano /casaOS/server/shell/11-usb-mount.rules`

You should have 2 lines that start with `KERNEL=="sd[a-z]*[0-9]"`.
Modify the regex to remove the name of your boot disk. For me with sda1 and sda2:
`KERNEL=="sd[a-z]*[3-9]"`

(Just change the regex to avoid 1 and 2 in the last character)
Save the file, try to reboot and it should be ok!

 My knowledge in bash code is really limited, so I guess a better solution would be to modify the `usb-mount.sh` file and add a check to avoid mounting boot disk.

**Comment by chest069** [comment]
Hello, I am experiencing the same issue as you but it still hangs even after doing the brute force solution have you you figured out anything more to why this happens?

`My original Fstab : 

proc            /proc           proc    defaults          0       0
PARTUUID=e357b633-01  /boot           vfat    defaults          0       2
PARTUUID=e357b633-02  /               ext4    defaults,noatime  0       1
# a swapfile is not a swap partition, no line here
#   use  dphys-swapfile swap[on|off]  for that
`
`My original Blkid : 
 
 blkid
/dev/sda1: LABEL_FATBOOT="boot" LABEL="boot" UUID="10EB-30C5" BLOCK_SIZE="512" TYPE="vfat" PARTUUID="e357b633-01"
/dev/sda2: LABEL="rootfs" UUID="223ecc81-7069-45f9-9309-c641eba776c8" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="e357b633-02"`

`Fstab after installing CasaOs : 

proc            /proc           proc    defaults          0       0
PARTUUID=e357b633-01  /boot           vfat    defaults          0       2
PARTUUID=e357b633-02  /               ext4    defaults,noatime  0       1
# a swapfile is not a swap partition, no line here
#   use  dphys-swapfile swap[on|off]  for that`

`Blkid after installing CasaOs :
 
/dev/sda1: LABEL_FATBOOT="boot" LABEL="boot" UUID="10EB-30C5" BLOCK_SIZE="512" TYPE="vfat" PARTUUID="e357b633-01"
/dev/sda2: LABEL="rootfs" UUID="223ecc81-7069-45f9-9309-c641eba776c8" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="e357b633-02"
`

Everything seems the same but I don't understand why this is happening

`/casaOS/server/shell/11-usb-mount.rules : 

KERNEL=="sd[a-z]*[0-9]", SUBSYSTEMS=="usb", ACTION=="add", RUN+="/bin/systemctl start usb-mount@%k.service"
KERNEL=="sd[a-z]*[0-9]", SUBSYSTEMS=="usb", ACTION=="remove", RUN+="/bin/systemctl stop usb-mount@%k.service`  

I wasn't sure what you were wanting changed here in the rules. Any help would be greatly appreciated. Thanks

**Comment by jerrykuku** [comment]
After our troubleshooting, this is caused by CasaOS mounting the USB device automatically. We have fixed this issue in v0.3.1, which will automatically disable the automatic mounting of USB disks if it is a Raspberry Pi device. You can update to the latest version to try it, if the problem still exists, please continue to feedback to me. 
You can check the update log here: https://github.com/IceWhaleTech/CasaOS/releases/tag/v0.3.1

**Comment by jerrykuku** [comment]
@tanmay-pathak I'm gonna close this issue for now. However if you see this problem happening again, please open a new issue and let the team know. Thanks!

**Comment by devcircus** [comment]
On 0.3.2.1 and still seeing this. My boot partition is mounted in casa, which causes the raspberry pi to give me the "emergency mode" when booting. Pressing enter allows booting to continue with no problems, but causes problems when I need to reboot remotely and can't press enter, plus I don't need my boot partition mounted inside casa.
