### ISSUE TITLE
[Feedback]power and temperature shown as 0.0W / 0C

### ISSUE THREAD

**Issue by romaniansuperhero** [IceWhaleTech/CasaOS#694]
### Description

power and temperature shown as 0.0W / 0C

acpi -t
Thermal 0: ok, 40.0 degrees C

paste <(cat /sys/class/thermal/thermal_zone*/type) <(cat /sys/class/thermal/thermal_zone*/temp) | column -s $'\t' -t | sed 's/\(.\)..$/.\1°C/'
acpitz  39.0°C

bord a68n-5745
https://www.biostar.com.tw/app/en/mb/introduction.php?S_ID=857#specification
AMD A10-5745(Quad core 2.1G, turbo 2.9G) processor
AMD A70M Chipset

### Additional Information

	 - OS: linux
	 - CasaOS Version: 0.3.8
	 - Disk Total: 54490 
	 - Disk Used: 9157 
	 - System Info: [Ubuntu 22.04.1 LTS   \l Bit:64 Mem:7111M Core:4 Linux pi-nas 5.15.0-53-generic #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux]
	 - Remote Version: 0.3.8
	 - Browser: Firefox 
	 - Version: 107.0

**Comment by mojothemonkey2** [comment]
thanks for the detailed ticket!
you provided all the info would have asked for already :)

so for this hardware, the thermal zone has a very generic name "acpitz". 
instead of trying to handle all the edge cases for cpu thermal zone names, I think we'll be better off falling back to zone0, when it's not one of the obvious cpu ones. 
I'll submit a change when I get a moment.

**Comment by mojothemonkey2** [comment]
So now if it can't match cpu name, it should do this:
```
{"level":"warn","ts":1669276097.285511,"msg":"CPU thermal zone not matched. Default to thermal_zone0.","func":"service.GetCPUThermalZone","file":"/code/mojothemonkey/CasaOS/service/system.go","line":335}
```
