### ISSUE TITLE
[Bug] App Stor: "context deadline exceeded" with Bazarr

### ISSUE THREAD

**Issue by mojothemonkey2** [IceWhaleTech/CasaOS#758]
**Describe the bug**
Err during Bazarr app install: Post "http://127.0.0.1:44275/v1/notify/install_app": context deadline exceeded

**To Reproduce**
App Store > Bazarr > Install.

**Expected behavior**
App installs.

**Screenshots**
Tried a few times, mostly it just hangs at X per cent, once it hung with the err.
The err also flashes up on the install page, in red.
But the same err is always seen from the log file.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Browser: Chrome
 - Version: CasaOS 0.4.0

**Logs**
/var/log/casaos/app-management.log:
```
2022-12-16T07:29:18.915Z        error   send install app by socket error:       {"error": "Post \"http://127.0.0.1:44275/v1/notify/install_app\": context deadline exceeded", "notify": {"name":"Bazarr","state":"PULLING","type":"INSTALL","icon":"https://cdn.jsdelivr.net/gh/IceWhaleTech/CasaOS-AppStore@main/Apps/Bazarr/icon.png","message":"{\"status\":\"Downloading\",\"progressDetail\":{\"current\":27453777,\"total\":118679674},\"progress\":\"[===========\\u003e                                       ]  27.45MB/118.7MB\",\"id\":\"6caae27c2f72\"}\r\n","finished":false,"success":true}, "func": "service.(*dockerService).DockerPullImage", "file": "/home/runner/work/CasaOS-AppManagement/CasaOS-AppManagement/service/docker.go", "line": 152}
```

**Additional context**
Doesn't happen so far with other apps, only Bazarr.
I did have Bazarr installed ok before. But since a full uninstall, it's not able to reinstall, hitting this err.

Thanks.

**Comment by mojothemonkey2** [comment]
Found a way to fix..

Although the app was uninstalled, including app data. Found that there was still some app data left.
So deleted this:
```
# rm -rf /DATA/AppData/bazarr        
```
Tried app install again - and worked first time.

So maybe there is a bug in deleting app data for uninstall? Leaving things in a bad state.

**Comment by mojothemonkey2** [comment]
Reproducing..

Uninstall Bazarr, including app data.
The app data folder is still left behind.
Try re-install Bazarr, and same err.

**Comment by mojothemonkey2** [comment]
Hit the err installing Bazarr, but this time WITHOUT the app data folder present.
So may just be coincidence - sometimes it works, most times it doesn't.

But definitely not removing the app data folder during uninstall+remove app data.

**Comment by tigerinus** [comment]
@mojothemonkey2 

The error happens when it takes more than 5 seconds for `CasaOS-AppManagement` service to send a pull progress notification to `CasaOS` service, which is highly unlikely to happen, because both services should be running on the same device, and there is not really a network constraint in between.

One possibility is that CasaOS is super slow or dead.

Please run thru following checklist:

- Run `top` before you repro the issue, see if CPU/RAM usage is high.
- Run `sudo journalctl -xef -u casaos` and see if you see any error in the output.
- Run `curl $(cat /var/run/casaos/casaos.url)` to see if you get `404 page not found` (expected - it shows service is at least running) or something else,

**Comment by mojothemonkey2** [comment]
Thanks for the info.
Yes, that makes sense since the issue was very intermittent, with no apparent pattern.
And cannot replicate since.

Had a look through the logs at the time, and can't see anything of interest around the error.
Will close.
