### ISSUE TITLE
[Bug] App name already exists

### ISSUE THREAD

**Issue by AuthorShin** [IceWhaleTech/CasaOS#808]
Sometimes when you install and uninstall the app when you want to install it again it will show you `App name already exists` error also I think it will occur when you install an app via CasaOS but remove it with other ways outside of CasaOS.

**Comment by raller1028** [comment]
CasaOS v0.4.1 added the clone application function to solve the problem

**Comment by raller1028** [comment]
Fixed by v0.4.1, please reopen if you have any problem.

**Comment by NebulaM57** [comment]
I am running 0.4.3 and I'm getting this same error/message.  Trying to install a custom app (mbentley/omada-controller:latest).  It installed the first time without a hitch.  But for some reason, it was pegging my CPU to 99%.  I had done some tweaking during the install and thot I may have hosed things up.  So I uninstalled it and tried to reinstall.  Now I get the "Already Exists" message and can't go any further with it.

Is there a path I can navigate to to remove old containers or clear files maybe?

Thank you

**Comment by zienhiet** [comment]
I am running 0.4.3 and am also having the same issue. I created a custom Calibre container using compose. Then I uninstalled the container and am attempting to re-create, but I get the "already exists" error. I've removed all references I could find to calibre, and a docker ps -a command does not show an calibre container.

**Comment by NebulaM57** [comment]
As of yesterday evening, I took a shot and tried to do the very same install again and it worked as expected.  I was able to install the mbentley/omada docker tag just fine.  So maybe it just takes time?  It’s been a couple of days since I had the issue before I tried again.  I don’t know.  I did nothing different.  But it worked this time.  

The issue can be closed for my part.  Thank you.
