### ISSUE TITLE
Container don't show after Watchtower update

### ISSUE THREAD

**Issue by hillaliy** [IceWhaleTech/CasaOS#97]
**Describe the bug**
I'm using watchtower to update my containers because there isn't update system on CasaOS.
After update the container works but don't show on CasaOS UI.

**Desktop
 - OS: ubuntu
 - Browser: safari
 - CasaOS Version 0.2.8

**Comment by LinkLeong** [comment]
casaos itself has a database to record if the application was installed through casaos. If the application name updated by watchtower has a corresponding record in casaos database, it can be shown, so the application name you updated is uuid?

**Comment by darnov01** [comment]
> casaos itself has a database to record if the application was installed through casaos. If the application name updated by watchtower has a corresponding record in casaos database, it can be shown, so the application name you updated is uuid?

Is it possible to have CasaOS set a specific name for a container so that this could be avoided?

**Comment by ajnart** [comment]
> > casaos itself has a database to record if the application was installed through casaos. If the application name updated by watchtower has a corresponding record in casaos database, it can be shown, so the application name you updated is uuid?
> 
> Is it possible to have CasaOS set a specific name for a container so that this could be avoided?

I was looking around in the code and this could be done by matching apps with the containers names instead of UUID. Even if those are automatically generated, they would not change when updating the image. What do you think about that change @LinkLeong ? 
Would be awesome if by default the container name would be equal to the app's name. It would make manually navigating in ``/APPDATA/`` a lot easier with readable folder names and solve the app update problem.

**Comment by hillaliy** [comment]
Hi I think is OK right now
